"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {AlertTriangle,Check,ChevronRight,Clipboard,Download,FileSpreadsheet,Filter,Library,Lightbulb,Search,Settings2,ShieldCheck,Sparkles,Upload} from "lucide-react";
import {Button} from "@/components/ui/button"; import {Input} from "@/components/ui/input"; import {Badge} from "@/components/ui/badge";
import {Fixture,potbelly,valleyFord,vendorRules,ConfigStatus} from "./configurator-data";
const labels:Record<ConfigStatus,string>={ready:"Ready",review:"Configure",factory:"Factory check",photometric:"Photometric",keep:"Keep specified"};
const csv=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`;
export default function Home(){
 const [project,setProject]=useState<"valley"|"potbelly">("valley"),[rows,setRows]=useState<Fixture[]>(valleyFord),[selected,setSelected]=useState("D1"),[filter,setFilter]=useState<"all"|ConfigStatus>("all"),[query,setQuery]=useState(""),[configured,setConfigured]=useState(false),[copied,setCopied]=useState(false),[notice,setNotice]=useState("");
 const officeInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{const saved=localStorage.getItem(`bobert-config-${project}`);if(saved){try{const parsed=JSON.parse(saved);setRows(parsed.rows);setConfigured(parsed.configured)}catch{}}},[project]);
 useEffect(()=>{localStorage.setItem(`bobert-config-${project}`,JSON.stringify({rows,configured}))},[project,rows,configured]);
 const active=rows.find(x=>x.type===selected)||rows[0]; const visible=rows.filter(x=>(filter==="all"||x.status===filter)&&`${x.type} ${x.specified} ${x.alternate} ${x.family}`.toLowerCase().includes(query.toLowerCase()));
 const total=rows.reduce((s,x)=>s+x.qty,0), exceptions=rows.filter(x=>["review","factory","photometric"].includes(x.status)).length, ready=rows.filter(x=>["ready","keep"].includes(x.status)).length, release=exceptions===0;
 const statusCounts=useMemo(()=>Object.fromEntries((["ready","review","factory","photometric","keep"] as ConfigStatus[]).map(s=>[s,rows.filter(x=>x.status===s).length])),[rows]);
 function switchProject(v:"valley"|"potbelly"){setProject(v);const saved=localStorage.getItem(`bobert-config-${v}`);if(saved){try{const parsed=JSON.parse(saved);setRows(parsed.rows);setConfigured(parsed.configured)}catch{setRows(v==="valley"?valleyFord:potbelly)}}else{setRows(v==="valley"?valleyFord:potbelly);setConfigured(v==="potbelly")};setSelected(v==="valley"?"D1":"L109");setFilter("all");setNotice("")}
 function updateQty(type:string,qty:number){setRows(r=>r.map(x=>x.type===type?{...x,qty:Math.max(0,qty||0),qtySource:"Manual override"}:x))}
 function updateCatalog(type:string,alternateCatalog:string){setRows(r=>r.map(x=>x.type===type?{...x,alternateCatalog,status:x.status==="keep"?"keep":"review",exception:"Catalog number entered; review before release."}:x))}
 function approve(type:string){const row=rows.find(x=>x.type===type);if(row?.status!=="keep"&&!row?.alternateCatalog){setNotice("Add a verified alternate catalog number before approving this fixture.");return}setRows(r=>r.map(x=>x.type===type?{...x,status:"ready",exception:"User reviewed and approved"}:x));setNotice(`${type} approved and saved.`)}
 function keepSpecified(type:string){setRows(r=>r.map(x=>x.type===type?{...x,alternate:x.specified,alternateCatalog:x.specifiedCatalog,status:"keep",exception:"Retained as specified by user."}:x));setNotice(`${type} retained as specified.`)}
 async function importOfficeCounts(file:File){const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);let matched=0;setRows(current=>current.map(row=>{for(const line of lines){const cells=line.split(/,|\t/).map(v=>v.trim().replace(/^"|"$/g,""));const qty=Number(cells[1]);if(cells[0]?.toUpperCase()===row.type.toUpperCase()&&Number.isFinite(qty)){matched++;return {...row,qty,qtySource:`Office count · ${file.name}`}}}return row}));setNotice(`${matched} office counts matched by fixture type. Unmatched rows were left unchanged.`)}
 const bom=rows.map(x=>[x.type,x.alternate,x.alternateCatalog||"",x.family,x.description,x.qty,x.qtySource,labels[x.status]].map(csv).join(","));
 function download(){const blob=new Blob([["TYPE","MANUFACTURER","CATALOG #","FAMILY","DESCRIPTION","QTY","QTY SOURCE","STATUS"].map(csv).join(",")+"\n"+bom.join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${project==="valley"?"Valley-Ford-of-Huron":"Potbelly"}-Alternate-BOM.csv`;a.click();URL.revokeObjectURL(a.href)}
 function createQuote(){if(!release)return;const quoteRows=rows.map(x=>[x.type,x.alternate,x.alternateCatalog||x.specifiedCatalog,"",x.description,x.qty].map(csv).join(","));const blob=new Blob([["TYPE","MANUFACTURER","CATALOG #","DIM","DESCRIPTION","QTY"].map(csv).join(",")+"\n"+quoteRows.join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${project==="valley"?"Valley-Ford-of-Huron":"Potbelly"}-Company-Quote-Import.csv`;a.click();URL.revokeObjectURL(a.href);setNotice("Released quote-import file created from approved alternates only.")}
 async function copy(){await navigator.clipboard.writeText(rows.map(x=>`${x.type}\t${x.alternate}\t${x.family}\t\t${x.description}\t${x.qty}`).join("\n"));setCopied(true);setTimeout(()=>setCopied(false),1200)}
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>B</span>bobert.ai</div><p>LIGHTING INTELLIGENCE</p><nav><button className="active"><Lightbulb/>Configurator</button><button><Library/>Knowledge</button><button><ShieldCheck/>Reviews</button><button><FileSpreadsheet/>Exports</button></nav><div className="side-note"><Sparkles/><strong>Shared company brain</strong><small>Every verified job improves the next one.</small></div></aside>
 <section className="workspace"><header className="topbar"><div><small>ACTIVE PROJECT</small><select value={project} onChange={e=>switchProject(e.target.value as "valley"|"potbelly")}><option value="valley">Valley Ford of Huron FS2.0</option><option value="potbelly">Potbelly — verified baseline</option></select></div><div className="top-actions"><input ref={officeInput} hidden type="file" accept=".csv,.tsv,.txt" onChange={e=>e.target.files?.[0]&&importOfficeCounts(e.target.files[0])}/><Button variant="outline" onClick={()=>officeInput.current?.click()}><Upload/>Import office counts</Button><Button variant="outline" onClick={copy}><Clipboard/>{copied?"Copied":"Copy quote rows"}</Button><Button onClick={download}><Download/>Export BOM</Button></div></header>{notice?<div className="notice page-notice">{notice}</div>:null}
 <div className="content"><section className="project-head"><div><p className="eyebrow">{project==="valley"?"CJI CONSTRUCTION · BID SET 07/30/2026":"VERIFIED PILOT"}</p><h1>{project==="valley"?"Valley Ford of Huron FS2.0":"Potbelly Sandwich Works"}</h1><p>{project==="valley"?"1530 Berlin Road, Huron, OH · Alternate package · Counts from drawing takeoff":"Locked baseline used to validate the full workflow"}</p></div><Button size="lg" onClick={()=>setConfigured(true)} disabled={configured}><Sparkles/>{configured?"Rules applied":"Build alternate package"}</Button></section>
 <section className="pipeline"><div className="done"><Check/>Intake</div><ChevronRight/><div className="done"><Check/>Drawing truth</div><ChevronRight/><div className={configured?"done":"current"}>{configured?<Check/>:<Settings2/>}Configure</div><ChevronRight/><div className={configured?"current":""}>Review exceptions</div><ChevronRight/><div className={release?"done":"locked"}>Excel quote</div></section>
 <section className="metrics"><article><strong>{rows.length}</strong><span>Fixture types</span></article><article><strong>{total}</strong><span>Total units</span></article><article><strong>{configured?ready:0}</strong><span>Assigned / retained</span></article><article className={exceptions?"warn":"good"}><strong>{configured?exceptions:"—"}</strong><span>Exceptions to review</span></article></section>
 {!configured?<section className="launch-card"><Sparkles/><div><h2>Drawing truth is ready</h2><p>One click applies LPA CSI’s vendor rules to the schedule, assigns preferred manufacturers, and preserves unmatched decorative fixtures.</p></div><Button onClick={()=>setConfigured(true)}>Build alternates</Button></section>:null}
 <section className="rules"><div><Settings2/><strong>Preferred vendor rules</strong></div>{vendorRules.map(r=><span key={r.match}>{r.match}<ChevronRight/><b>{r.target}</b></span>)}</section>
 <section className="work-grid"><article className="table-card"><div className="toolbar"><div><h2>Configurator</h2><p>Automation handles the normal path. Review only flagged exceptions.</p></div><div className="search"><Search/><Input placeholder="Search fixtures" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
 <div className="filters"><button className={filter==="all"?"on":""} onClick={()=>setFilter("all")}><Filter/>All {rows.length}</button>{(["ready","review","factory","photometric","keep"] as ConfigStatus[]).map(s=><button key={s} className={filter===s?"on":""} onClick={()=>setFilter(s)}>{labels[s]} {statusCounts[s]}</button>)}</div>
 <div className="table-wrap"><table><thead><tr><th>Type</th><th>Drawing truth</th><th>Preferred alternate</th><th>Qty</th><th>Status</th></tr></thead><tbody>{visible.map(x=><tr key={x.type} className={selected===x.type?"selected":""} onClick={()=>setSelected(x.type)}><td><b>{x.type}</b><small>{x.area}</small></td><td><b>{x.specified}</b><small>{x.description}</small></td><td><b>{configured?x.alternate:"Pending"}</b><small>{configured?x.family:"Run configurator"}</small></td><td><Input type="number" value={x.qty} onClick={e=>e.stopPropagation()} onChange={e=>updateQty(x.type,+e.target.value)}/><small>{x.qtySource}</small></td><td><Badge className={`status ${configured?x.status:"pending"}`}>{configured?labels[x.status]:"Pending"}</Badge></td></tr>)}</tbody></table></div></article>
 <aside className="review"><div className="review-top"><span>{active.type}</span><Badge className={`status ${active.status}`}>{labels[active.status]}</Badge></div><h2>{active.alternate}</h2><p className="family">{active.family}</p><div className="truth"><small>SPECIFIED BASIS</small><strong>{active.specified}</strong><code>{active.specifiedCatalog}</code></div><div className="catalog-entry"><small>VERIFIED ALTERNATE CATALOG #</small><Input value={active.alternateCatalog||""} onChange={e=>updateCatalog(active.type,e.target.value)} placeholder="Enter or paste confirmed catalog number"/></div><div className="requirements"><small>NORMALIZED REQUIREMENTS</small>{active.requirements.map(r=><span key={r}>{r}</span>)}</div><div className={`exception ${active.status}`}><AlertTriangle/><div><small>AUTOMATION DECISION</small><p>{active.exception||"No exception recorded."}</p></div></div><div className="source"><ShieldCheck/><p><b>Quantity traceable</b><br/>{active.qty} units · {active.qtySource}</p></div>{!["ready","keep"].includes(active.status)?<div className="review-actions"><Button variant="outline" onClick={()=>keepSpecified(active.type)}>Keep specified</Button><Button onClick={()=>approve(active.type)}><Check/>Approve alternate</Button></div>:<Button className="full" variant="outline"><Check/>Ready for BOM</Button>}</aside></section>
 <section className={`release ${release?"open":"blocked"}`}><div>{release?<ShieldCheck/>:<AlertTriangle/>}<div><h2>{release?"Company quote export ready":"Company quote export is protected"}</h2><p>{release?"All fixture lines passed review and can be written into the locked quote template.":`${exceptions} fixture types still need configuration, factory confirmation, or photometric review. Review CSV remains available.`}</p></div></div><Button disabled={!release} onClick={createQuote}><FileSpreadsheet/>Create quote import</Button></section>
 </div></section></main>}
