/**
 * Generates drizzle/seed/0001_seed_pilot_projects.sql from the live
 * configurator-data.ts. Run with:
 *   npx tsx drizzle/seed/generate-seed.ts > drizzle/seed/0001_seed_pilot_projects.sql
 *
 * Why generate instead of hand-write: valleyFord (26 fixture types) and
 * potbelly (6 fixture types) are the actual pilot/demo data currently
 * hardcoded in the app. Transcribing 32 rows by hand risks silent
 * mismatches against what's live. This script is the only source of truth
 * for the seed — re-run it if configurator-data.ts changes before the
 * seed has been applied to D1.
 */
import { valleyFord, potbelly, vendorRules, type Fixture } from "../../app/configurator-data";

function esc(v: string | number | boolean): string {
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "number") return String(v);
  return `'${String(v).replaceAll("'", "''")}'`;
}

function projectInsert(opts: {
  name: string;
  location: string;
  eyebrow: string;
  summary: string;
  defaultSelectedFixtureType: string;
  status: string;
}): string {
  return `INSERT INTO projects (name, location, eyebrow, summary, default_selected_fixture_type, status)
VALUES (${esc(opts.name)}, ${esc(opts.location)}, ${esc(opts.eyebrow)}, ${esc(opts.summary)}, ${esc(opts.defaultSelectedFixtureType)}, ${esc(opts.status)});`;
}

function fixtureInserts(projectName: string, rows: Fixture[]): string[] {
  return rows.map((x) => {
    const requirements = JSON.stringify(x.requirements ?? []);
    return `INSERT INTO fixtures (project_id, fixture_type, area, specified_manufacturer, specified_catalog, alternate_manufacturer, alternate_catalog, family, description, quantity, quantity_source, review_status, exception, requirements, out_of_scope)
VALUES ((SELECT id FROM projects WHERE name = ${esc(projectName)}), ${esc(x.type)}, ${esc(x.area)}, ${esc(x.specified)}, ${esc(x.specifiedCatalog)}, ${esc(x.alternate)}, ${esc(x.alternateCatalog ?? "")}, ${esc(x.family)}, ${esc(x.description)}, ${x.qty}, ${esc(x.qtySource)}, ${esc(x.status)}, ${esc(x.exception)}, ${esc(requirements)}, ${esc(!!x.outOfScope)});`;
  });
}

function vendorRuleInserts(): string[] {
  return vendorRules.map(
    (r) =>
      `INSERT INTO vendor_rules (match_label, target_manufacturer, includes_terms)
VALUES (${esc(r.match)}, ${esc(r.target)}, ${esc(r.includes)});`
  );
}

const lines: string[] = [
  "-- Generated by drizzle/seed/generate-seed.ts — do not hand-edit.",
  "-- Seeds the two pilot/demo projects (Valley Ford, Potbelly) as real",
  "-- rows, plus the three default vendor rules, so the app has no",
  "-- client-side special-casing left for them once D1 is wired in.",
  "",
  "-- Valley Ford of Huron FS2.0",
  projectInsert({
    name: "Valley Ford of Huron FS2.0",
    location: "1530 Berlin Road, Huron, OH",
    eyebrow: "CJI CONSTRUCTION · BID SET 07/30/2026",
    summary: "Alternate package · Counts from drawing takeoff",
    defaultSelectedFixtureType: "D1",
    status: "intake",
  }),
  ...fixtureInserts("Valley Ford of Huron FS2.0", valleyFord),
  "",
  "-- Potbelly Sandwich Works (verified pilot)",
  projectInsert({
    name: "Potbelly Sandwich Works",
    location: "",
    eyebrow: "VERIFIED PILOT",
    summary: "Locked baseline used to validate the full workflow",
    defaultSelectedFixtureType: "L109",
    status: "configured",
  }),
  ...fixtureInserts("Potbelly Sandwich Works", potbelly),
  "",
  "-- Default vendor rules",
  ...vendorRuleInserts(),
  "",
];

process.stdout.write(lines.join("\n") + "\n");
